modLoader="javafml"
loaderVersion="${mod_forge_version}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/xxx/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/xxx"
# logoFile="modenforcer.png"
# credits=""
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_vendor}"
updateJSONURL="http://maxhenkel.de/update/modenforcer.json"
description='''Mod Enforcer'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"